# Generated by Django 3.2.5 on 2021-07-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NEWSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(auto_created=True, verbose_name='Status')),
                ('name', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_of_update', models.DateTimeField(auto_now_add=True, verbose_name='Date of update')),
                ('image', models.ImageField(upload_to='', verbose_name='News Image')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NEWSS.themes')),
            ],
        ),
    ]
